# Hand-drawn 16x16 site icons. Edit the grids here, then run: python3 art/src/icons/_make.py
LEGEND = {"k": "ink", "w": "paper", "G": "grey-3", "g": "grey-2", "o": "act-2", "O": "act-1", "h": "act-3", "e": "ok-2", "E": "ok-1"}
ICONS = {
"coin": """
................
.....kkkkkk.....
...kkhhhhhhkk...
..khhooooooOOk..
..khookkkkoOOk..
.khookoooooOOOk.
.khookoooooooOk.
.khooookkkooOOk.
.khooooooookoOk.
.khooooooookoOk.
.kOookkkkkkooOk.
..kOooooooooOk..
..kOOOooooOOOk..
...kkOOOOOOkk...
.....kkkkkk.....
................""",
"unlocked": """
................
.....kkkkkk.....
....kGGGGGGk....
...kGkkkkkkGk...
...kGk....kGk...
...kGk.....k....
...kGk..........
.kkkkkkkkkkkkkk.
.kooooooooooooOk
.kohhhhhhhhhhoOk
.kooooookkooooOk
.kooooookkooooOk
.koooooookoooOOk
.kOOOOOOOOOOOOOk
.kkkkkkkkkkkkkkk
................""",
"chip": """
................
...k.k.k.k.k....
...k.k.k.k.k....
.kkkkkkkkkkkkk..
.kGGGGGGGGGGGk..
kkGkkkkkkkkkGkk.
.kGkoooooooOkGk.
kkGkoOkkkhoOkGkk
.kGkoOkooooOkGk.
kkGkoOkkkooOkGkk
.kGkooooooOOkGk.
kkGkkkkkkkkkkGkk
.kGGGGGGGGGGGGk.
.kkkkkkkkkkkkkk.
...k.k.k.k.k....
...k.k.k.k.k....""",
"subscription": """
................
..kk......kk....
.kkkkkkkkkkkkkk.
.kOOOOOOOOOOOOk.
.kOOOOOOOOOOOOk.
.kkkkkkkkkkkkkk.
.kwwwwwwwwwwwwk.
.kwkkwkkwkkwwwk.
.kwkkwkkwkkwwwk.
.kwwwwwwwwwwwwk.
.kwkkwkkwoowwwk.
.kwkkwkkwoowwwk.
.kwwwwwwwwwwwwk.
.kkkkkkkkkkkkkk.
................
................""",
"token": """
................
.......kk.......
.....kkhhkk.....
...kkhhoooOkk...
..khhooooooOOk..
..khoookkoooOk..
..khookwwkooOk..
..khookwwkooOk..
..khoookkoooOk..
..khooooooooOk..
..kOOooooooOOk..
...kkOOooOOkk...
.....kkOOkk.....
.......kk.......
................
................""",
"envelope": """
................
................
.kkkkkkkkkkkkkk.
.kwkwwwwwwwwkwk.
.kwwkwwwwwwkwwk.
.kwwwkwwwwkwwwk.
.kwwwwkwwkwwwwk.
.kwwwwwkkwwwwwk.
.kwwwwwwwwwwwwk.
.kwwwwwwwwwoooO.
.kwwwwwwwwwoooO.
.kGGGGGGGGGOOOO.
.kkkkkkkkkkkkkk.
................
................
................""",
"status": """
................
................
.....kkkkkk.....
....keeeeeEk....
...keewweeeEk...
...keweeeeeEk...
...keeeeeeeEk...
...keeeeeeeEk...
...kEeeeeeEEk...
....kEEEEEEk....
.....kkkkkk.....
......kggk......
....kkkkkkkk....
....kggggggk....
....kkkkkkkk....
................""",
}
import pathlib
out = pathlib.Path(__file__).parent
legend = "legend:\n" + "".join(f"  {k} = {v}\n" for k, v in LEGEND.items())
for name, grid in ICONS.items():
    rows = grid.strip("\n").splitlines()
    assert len(rows) == 16 and all(len(r) == 16 for r in rows), (name, [len(r) for r in rows])
    (out / f"{name}.txt").write_text(f"size: 16x16\npalette: site\nframes: 1\ncategory: icon\n{legend}frame 1:\n" + "\n".join(rows) + "\n")
